-- Typed models for the Valorant SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Agent
---@field abilities? table
---@field assetPath? string
---@field background? string
---@field backgroundGradientColors? table
---@field bustPortrait? string
---@field characterTags? table
---@field description? string
---@field developerName? string
---@field displayIcon? string
---@field displayIconSmall? string
---@field displayName? string
---@field fullPortrait? string
---@field fullPortraitV2? string
---@field isAvailableForTest? boolean
---@field isBaseContent? boolean
---@field isFullPortraitRightFacing? boolean
---@field isPlayableCharacter? boolean
---@field killfeedPortrait? string
---@field role? table
---@field uuid? string
---@field voiceLine? table

---@class AgentLoadMatch
---@field id string

---@class AgentListMatch
---@field abilities? table
---@field assetPath? string
---@field background? string
---@field backgroundGradientColors? table
---@field bustPortrait? string
---@field characterTags? table
---@field description? string
---@field developerName? string
---@field displayIcon? string
---@field displayIconSmall? string
---@field displayName? string
---@field fullPortrait? string
---@field fullPortraitV2? string
---@field isAvailableForTest? boolean
---@field isBaseContent? boolean
---@field isFullPortraitRightFacing? boolean
---@field isPlayableCharacter? boolean
---@field killfeedPortrait? string
---@field role? table
---@field uuid? string
---@field voiceLine? table

---@class Competitive
---@field assetObjectName? string
---@field assetPath? string
---@field tiers? table
---@field uuid? string

---@class CompetitiveListMatch
---@field assetObjectName? string
---@field assetPath? string
---@field tiers? table
---@field uuid? string

---@class Cosmetic
---@field animationGif? string
---@field animationPng? string
---@field assetPath? string
---@field category? string
---@field displayIcon? string
---@field displayName? string
---@field fullIcon? string
---@field fullTransparentIcon? string
---@field hideIfNotOwned? boolean
---@field isHiddenIfNotOwned? boolean
---@field isNullSpray? boolean
---@field largeArt? string
---@field levels? table
---@field smallArt? string
---@field themeUuid? string
---@field uuid? string
---@field wideArt? string

---@class CosmeticListMatch
---@field animationGif? string
---@field animationPng? string
---@field assetPath? string
---@field category? string
---@field displayIcon? string
---@field displayName? string
---@field fullIcon? string
---@field fullTransparentIcon? string
---@field hideIfNotOwned? boolean
---@field isHiddenIfNotOwned? boolean
---@field isNullSpray? boolean
---@field largeArt? string
---@field levels? table
---@field smallArt? string
---@field themeUuid? string
---@field uuid? string
---@field wideArt? string

---@class GameMode
---@field allowsMatchTimeouts? boolean
---@field assetPath? string
---@field displayIcon? string
---@field displayName? string
---@field duration? string
---@field economyType? string
---@field gameFeatureOverrides? table
---@field gameRuleBoolOverrides? table
---@field isMinimapHidden? boolean
---@field isTeamVoiceAllowed? boolean
---@field orbCount? number
---@field roundsPerHalf? number
---@field teamRoles? table
---@field uuid? string

---@class GameModeListMatch
---@field allowsMatchTimeouts? boolean
---@field assetPath? string
---@field displayIcon? string
---@field displayName? string
---@field duration? string
---@field economyType? string
---@field gameFeatureOverrides? table
---@field gameRuleBoolOverrides? table
---@field isMinimapHidden? boolean
---@field isTeamVoiceAllowed? boolean
---@field orbCount? number
---@field roundsPerHalf? number
---@field teamRoles? table
---@field uuid? string

---@class Map
---@field assetPath? string
---@field callouts? table
---@field coordinates? string
---@field displayIcon? string
---@field displayName? string
---@field listViewIcon? string
---@field mapUrl? string
---@field narrativeDescription? string
---@field splash? string
---@field tacticalDescription? string
---@field uuid? string
---@field xMultiplier? number
---@field xScalarToAdd? number
---@field yMultiplier? number
---@field yScalarToAdd? number

---@class MapLoadMatch
---@field id string

---@class MapListMatch
---@field assetPath? string
---@field callouts? table
---@field coordinates? string
---@field displayIcon? string
---@field displayName? string
---@field listViewIcon? string
---@field mapUrl? string
---@field narrativeDescription? string
---@field splash? string
---@field tacticalDescription? string
---@field uuid? string
---@field xMultiplier? number
---@field xScalarToAdd? number
---@field yMultiplier? number
---@field yScalarToAdd? number

---@class Weapon
---@field assetPath? string
---@field category? string
---@field defaultSkinUuid? string
---@field displayIcon? string
---@field displayName? string
---@field killStreamIcon? string
---@field shopData? table
---@field skins? table
---@field uuid? string
---@field weaponStats? table

---@class WeaponLoadMatch
---@field id string

---@class WeaponListMatch
---@field assetPath? string
---@field category? string
---@field defaultSkinUuid? string
---@field displayIcon? string
---@field displayName? string
---@field killStreamIcon? string
---@field shopData? table
---@field skins? table
---@field uuid? string
---@field weaponStats? table

local M = {}

return M
